feature: comment CRUD 기능 구현
cathaaaaand/woori_forei-BE pull request #115
Opened 2024-05-04 14:00 UTC by daeundada

1. 댓글 CRUD 기능 구현 완료 했습니다.
2. 댓글 생성시 csrf 필터에서 403 에러가 발생해서 예외처리 해주었습니다.
3. 댓글 ErrorCode 추가해줬습니다.
4. 그외 어노테이션, setter 제거등 약간의 코드 수정을 했습니다.

2024-05-04 14:19 UTC, EUNCHAEv1006 requested changes

2024-05-04 14:19 UTC, EUNCHAEv1006 commented on src/main/java/dnaaaaahtac/wooriforei/domain/comment/controller/CommentController.java
> +    @GetMapping("/{boardId}")
수정 부탁티비

2024-05-04 14:19 UTC, EUNCHAEv1006 commented on src/main/java/dnaaaaahtac/wooriforei/domain/comment/dto/CommentRequestDTO.java
> +    String commentContent;
아주 마음에 들어요. commentContent 구우우웃

2024-05-04 14:19 UTC, EUNCHAEv1006 commented on src/main/java/dnaaaaahtac/wooriforei/domain/comment/service/CommentService.java
> +
의도한 개행인가요

2024-05-04 14:19 UTC, EUNCHAEv1006 commented on src/main/java/dnaaaaahtac/wooriforei/domain/image/dto/ImageSaveDTO.java
> -@Setter
크 베리굿

2024-05-04 14:19 UTC, EUNCHAEv1006 commented on src/main/java/dnaaaaahtac/wooriforei/global/config/WebSecurityConfig.java
> +                .csrf(csrf -> csrf.ignoringRequestMatchers("/api/auth/**", "/api/images/**", "/api/communities/**","/api/comments/**")) // 특정 경로에서만 CSRF 비활성화
띄어쓰기 부탁해도 될까요 ㅎ
`"/api/auth/**", "/api/images/**", "/api/communities/**", "/api/comments/**"`

2024-05-04 15:44 UTC, daeundada commented on src/main/java/dnaaaaahtac/wooriforei/domain/comment/controller/CommentController.java
> +    @GetMapping("/{boardId}")
해당 api 삭제후 게시글 조회때 댓글 조회되도록 했습니다

2024-05-04 15:45 UTC, daeundada commented on src/main/java/dnaaaaahtac/wooriforei/global/config/WebSecurityConfig.java
> +                .csrf(csrf -> csrf.ignoringRequestMatchers("/api/auth/**", "/api/images/**", "/api/communities/**","/api/comments/**")) // 특정 경로에서만 CSRF 비활성화
수정 했습니다.

2024-05-05 13:37 UTC, EUNCHAEv1006 approved these changes

2024-05-06 09:53 UTC, merged